default:
  model_ver: "DEV"

  # Model specs & features
  target_col: "dna_outcome"
  vars:
    - "local_spec_code"
    - "national_spec_code"
    - "appointment_type"
    - "distance_km"
    - "nfa_ind"
    - "age_group"
    - "age_at_appointment"
    - "ethnicity"
    - "a_ld"
    - "a_autism"
    - "a_interpreter_req_bsl"
    - "a_interpreter_req_lang"
    - "a_balance"
    - "a_cognitive_impairment"
    - "a_mobility_restriction"
    - "a_hear_vis_impaired"
    - "a_dementia"
    - "a_depression"
    - "a_downs_syndrome"
    - "a_long_standing_condition"
    - "a_makaton"
    - "a_mild_cognitive_impairment"
    - "a_memory_impairment"
    - "a_mood_disorder"
    - "a_other_disability"
    - "a_psychosis"
    - "a_severe_anxiety"
    - "a_wheelchair_user"
    - "gender"
    - "registered_gp_practice"
    - "site_code"
    - "prev_dna_ly"
    - "appt_hour"
    - "appt_dow"
    - "appt_month"
    - "appt_wknd_ind"
    - "referral_urgency"
    - "lead_time_days"
    - "clinic_code"
    - "clinic_location"
    - "imd"
    
  new_appointment_path: "data/new_clinic_appointments.csv"

  # Execution flags
  tune_model: false
  num_threads: 4
  num_workers: 6

  # Model tuning
  cv_folds: 10
  grid_size: 25

  # Random Forest hyperparams
  tree_range: [250, 1000]
  mtry: 2
  trees: 468
  min_n: 6
  fct_other_prp: 0.02